// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: rpc_message.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetaValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ints          []int64                `protobuf:"varint,1,rep,packed,name=ints,proto3" json:"ints,omitempty"`
	Strs          []string               `protobuf:"bytes,2,rep,name=strs,proto3" json:"strs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaValues) Reset() {
	*x = MetaValues{}
	mi := &file_rpc_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaValues) ProtoMessage() {}

func (x *MetaValues) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaValues.ProtoReflect.Descriptor instead.
func (*MetaValues) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{0}
}

func (x *MetaValues) GetInts() []int64 {
	if x != nil {
		return x.Ints
	}
	return nil
}

func (x *MetaValues) GetStrs() []string {
	if x != nil {
		return x.Strs
	}
	return nil
}

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kvs           map[string]*MetaValues `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_rpc_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{1}
}

func (x *Meta) GetKvs() map[string]*MetaValues {
	if x != nil {
		return x.Kvs
	}
	return nil
}

type RpcRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint32                 `protobuf:"fixed32,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	MethodName    string                 `protobuf:"bytes,3,opt,name=methodName,proto3" json:"methodName,omitempty"`
	Md            *Meta                  `protobuf:"bytes,4,opt,name=md,proto3" json:"md,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequestMessage) Reset() {
	*x = RpcRequestMessage{}
	mi := &file_rpc_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequestMessage) ProtoMessage() {}

func (x *RpcRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequestMessage.ProtoReflect.Descriptor instead.
func (*RpcRequestMessage) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{2}
}

func (x *RpcRequestMessage) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RpcRequestMessage) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RpcRequestMessage) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *RpcRequestMessage) GetMd() *Meta {
	if x != nil {
		return x.Md
	}
	return nil
}

func (x *RpcRequestMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RpcResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint32                 `protobuf:"fixed32,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ecode         int32                  `protobuf:"varint,2,opt,name=ecode,proto3" json:"ecode,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Md            *Meta                  `protobuf:"bytes,4,opt,name=md,proto3" json:"md,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponseMessage) Reset() {
	*x = RpcResponseMessage{}
	mi := &file_rpc_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponseMessage) ProtoMessage() {}

func (x *RpcResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponseMessage.ProtoReflect.Descriptor instead.
func (*RpcResponseMessage) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{3}
}

func (x *RpcResponseMessage) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RpcResponseMessage) GetEcode() int32 {
	if x != nil {
		return x.Ecode
	}
	return 0
}

func (x *RpcResponseMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RpcResponseMessage) GetMd() *Meta {
	if x != nil {
		return x.Md
	}
	return nil
}

func (x *RpcResponseMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_rpc_message_proto protoreflect.FileDescriptor

const file_rpc_message_proto_rawDesc = "" +
	"\n" +
	"\x11rpc_message.proto\"4\n" +
	"\n" +
	"MetaValues\x12\x12\n" +
	"\x04ints\x18\x01 \x03(\x03R\x04ints\x12\x12\n" +
	"\x04strs\x18\x02 \x03(\tR\x04strs\"m\n" +
	"\x04Meta\x12 \n" +
	"\x03kvs\x18\x01 \x03(\v2\x0e.Meta.KvsEntryR\x03kvs\x1aC\n" +
	"\bKvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.MetaValuesR\x05value:\x028\x01\"\x98\x01\n" +
	"\x11RpcRequestMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\aR\x03seq\x12 \n" +
	"\vserviceName\x18\x02 \x01(\tR\vserviceName\x12\x1e\n" +
	"\n" +
	"methodName\x18\x03 \x01(\tR\n" +
	"methodName\x12\x15\n" +
	"\x02md\x18\x04 \x01(\v2\x05.MetaR\x02md\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\x83\x01\n" +
	"\x12RpcResponseMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\aR\x03seq\x12\x14\n" +
	"\x05ecode\x18\x02 \x01(\x05R\x05ecode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x15\n" +
	"\x02md\x18\x04 \x01(\v2\x05.MetaR\x02md\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayloadB\aZ\x05./rpcb\x06proto3"

var (
	file_rpc_message_proto_rawDescOnce sync.Once
	file_rpc_message_proto_rawDescData []byte
)

func file_rpc_message_proto_rawDescGZIP() []byte {
	file_rpc_message_proto_rawDescOnce.Do(func() {
		file_rpc_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_message_proto_rawDesc), len(file_rpc_message_proto_rawDesc)))
	})
	return file_rpc_message_proto_rawDescData
}

var file_rpc_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_message_proto_goTypes = []any{
	(*MetaValues)(nil),         // 0: MetaValues
	(*Meta)(nil),               // 1: Meta
	(*RpcRequestMessage)(nil),  // 2: RpcRequestMessage
	(*RpcResponseMessage)(nil), // 3: RpcResponseMessage
	nil,                        // 4: Meta.KvsEntry
}
var file_rpc_message_proto_depIdxs = []int32{
	4, // 0: Meta.kvs:type_name -> Meta.KvsEntry
	1, // 1: RpcRequestMessage.md:type_name -> Meta
	1, // 2: RpcResponseMessage.md:type_name -> Meta
	0, // 3: Meta.KvsEntry.value:type_name -> MetaValues
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_message_proto_init() }
func file_rpc_message_proto_init() {
	if File_rpc_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_message_proto_rawDesc), len(file_rpc_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_message_proto_goTypes,
		DependencyIndexes: file_rpc_message_proto_depIdxs,
		MessageInfos:      file_rpc_message_proto_msgTypes,
	}.Build()
	File_rpc_message_proto = out.File
	file_rpc_message_proto_goTypes = nil
	file_rpc_message_proto_depIdxs = nil
}
